from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Dict

from app.config import ensure_directories, validate_config
from app.utils.utils import build_output_path, save_json
from app.graph.workflow import get_compiled_graph


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Run the multi-agent dyslexia assessment workflow for one subject."
    )

    parser.add_argument(
        "--case-csv",
        type=str,
        required=True,
        help="Path to the subject-level feature CSV file.",
    )

    parser.add_argument(
        "--subject-id",
        type=str,
        required=True,
        help="Subject ID to assess.",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Optional custom output directory. If not provided, the default from config is used.",
    )

    parser.add_argument(
        "--mode",
        type=str,
        default="holdout",
        choices=["holdout", "cv", "demo"],
        help="Execution mode. Default: holdout.",
    )

    parser.add_argument(
        "--aoi-profile-json",
        type=str,
        default=None,
        help=(
            "Path to AOI difficulty profile JSON generated by "
            "scripts/prepare_features_with_aoi.py."
        ),
    )

    parser.add_argument(
        "--syllables-model-path",
        type=str,
        default=None,
        help="Optional path to the trained Syllables model.",
    )

    parser.add_argument(
        "--meaningful-model-path",
        type=str,
        default=None,
        help="Optional path to the trained MeaningfulText model.",
    )

    parser.add_argument(
        "--pseudotext-model-path",
        type=str,
        default=None,
        help="Optional path to the trained PseudoText model.",
    )

    parser.add_argument(
        "--pretty-print",
        action="store_true",
        help="Print the final assessment nicely to the console.",
    )

    return parser.parse_args()


def print_specific_difficulties(final_report: Dict[str, Any]) -> None:
    """
    Print concrete difficulty points from specialist reports.
    """
    specialist_reports = final_report.get("specialist_reports", [])

    print("\n=== Specific Difficulties by Specialist ===")

    has_any = False

    for report in specialist_reports:
        task_name = report.get("task_name", "UnknownTask")
        difficulties = report.get("specific_difficulties", [])

        print(f"\n[{task_name}]")

        if not difficulties:
            print("No concrete AOI-level difficulty was available.")
            continue

        has_any = True

        for idx, item in enumerate(difficulties[:5], start=1):
            unit = item.get("unit", "")
            category = item.get("unit_category", "")
            location = item.get("location", "")
            severity = item.get("severity", "")
            focus = item.get("suggested_focus", "")

            print(
                f"{idx}. unit='{unit}' | category={category} | "
                f"location={location} | severity={severity}"
            )
            # print(f"   focus: {focus}")

    if not has_any:
        print("\nNo concrete AOI-level difficulties were found in any specialist report.")


def print_intervention_suggestions(final_report: Dict[str, Any]) -> None:
    """
    Print Board Agent intervention suggestions.
    """
    final_assessment = final_report.get("final_assessment", {})
    suggestions = final_assessment.get("intervention_suggestions", [])

    print("\n=== Expert-Facing Intervention Suggestions ===")

    if not suggestions:
        print("No intervention suggestions were generated.")
        return

    for idx, item in enumerate(suggestions, start=1):
        focus_area = item.get("focus_area", "")
        reason = item.get("reason", "")
        suggested_action = item.get("suggested_action", "")
        priority = item.get("priority", "")

        print(f"{idx}. {focus_area} | priority={priority}")
        print(f"   Reason: {reason}")
        print(f"   Suggested action: {suggested_action}")


def print_final_summary(final_report: Dict[str, Any]) -> None:
    """
    Print a concise summary of the final assessment.
    """
    final_assessment = final_report["final_assessment"]
    critic_report = final_report["critic_report"]

    print("\n=== Final Assessment Summary ===")
    print(f"Subject ID         : {final_report['subject_id']}")
    print(f"Final Risk Level   : {final_assessment['final_risk_level']}")
    print(f"Overall Confidence : {final_assessment['overall_confidence']:.3f}")
    print(f"Agreement Level    : {final_assessment['agreement_level']}")
    print(f"Critic Verdict     : {critic_report['verdict']}")

    print("\nIntegrated rationale:")
    print(final_assessment["integrated_rationale"])

    print("\nUncertainty note:")
    print(final_assessment["uncertainty_note"])

    print("\nRecommendation:")
    print(final_assessment["recommendation"])

    specific_summary = final_assessment.get("specific_difficulty_summary", [])
    if specific_summary:
        print("\nSpecific difficulty summary:")
        for idx, item in enumerate(specific_summary, start=1):
            print(f"{idx}. {item}")

    # print_specific_difficulties(final_report)
    print_intervention_suggestions(final_report)

    print("\n================================\n")


def main() -> None:
    """
    Entry point for the dyslexia multi-agent workflow.

    Steps:
    1. Validate config and create required directories
    2. Parse runtime arguments
    3. Build the compiled LangGraph workflow
    4. Invoke the workflow on one subject
    5. Save the final JSON report
    6. Print the final result
    """
    args = parse_args()

    try:
        validate_config()
        ensure_directories()

        graph = get_compiled_graph()

        initial_state: Dict[str, Any] = {
            "case_csv": args.case_csv,
            "subject_id": args.subject_id,
            "output_dir": args.output_dir,
            "mode": args.mode,
        }

        if args.aoi_profile_json:
            initial_state["aoi_profile_json"] = args.aoi_profile_json

        if args.syllables_model_path:
            initial_state["syllables_model_path"] = args.syllables_model_path

        if args.meaningful_model_path:
            initial_state["meaningful_model_path"] = args.meaningful_model_path

        if args.pseudotext_model_path:
            initial_state["pseudotext_model_path"] = args.pseudotext_model_path

        result = graph.invoke(initial_state)

        if "final_report" not in result:
            raise ValueError(
                "Workflow execution completed, but no 'final_report' was returned."
            )

        final_report = result["final_report"]

        output_path = build_output_path(
            subject_id=args.subject_id,
            output_dir=args.output_dir,
        )
        save_json(output_path, final_report)

        print(f"Saved final report to: {output_path}")

        if args.pretty_print:
            print_final_summary(final_report)
        else:
            print(
                json.dumps(
                    final_report["final_assessment"],
                    indent=2,
                    ensure_ascii=False,
                )
            )

    except Exception as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()