from __future__ import annotations

from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field


# =============================================================================
# Evidence schemas
# =============================================================================

class EvidenceItem(BaseModel):
    feature: str
    value: Union[float, str]
    importance: float = Field(..., ge=0.0)
    evidence_type: Literal[
        "eye_tracking",
        "fixation",
        "saccade",
        "global_metric",
        "linguistic",
        "interaction",
    ]
    direction: Literal["higher", "lower", "mixed"]
    note: str


class DifficultyItem(BaseModel):
    """
    A concrete AOI/textual unit where the child showed effortful reading behavior.

    Important:
    Specialist agents should NOT suggest intervention here.
    They should only report what was observed:
    - which unit,
    - where,
    - what evidence,
    - how severe relative to other AOIs in the same task.

    Board Agent is responsible for converting these observations into
    expert-facing intervention_suggestions.
    """

    unit: str
    unit_category: Literal[
        "short_unit",
        "regular_unit",
        "complex_or_long_unit",
        "unknown",
    ]
    location: str
    evidence: str
    severity: Literal["low", "medium", "high"]


class InterventionSuggestion(BaseModel):
    """
    Expert-facing recommendation generated by the Assessment Board Agent.

    These suggestions should be linked to observed specialist evidence,
    not generic advice.
    """

    focus_area: str
    reason: str
    suggested_action: str
    priority: Literal["low", "medium", "high"]


# =============================================================================
# Agent report schemas
# =============================================================================

class SpecialistReport(BaseModel):
    """
    Output schema for each specialist agent:
    - Syllables Agent
    - MeaningfulText Agent
    - PseudoText Agent

    Specialist responsibility:
    - run task-specific model,
    - report risk score,
    - report eye-tracking / linguistic / interaction evidence,
    - report concrete AOI-level difficulties,
    - provide a short task-level interpretation.

    Specialist should NOT recommend intervention actions.
    """

    task_name: Literal["Syllables", "MeaningfulText", "PseudoText"]

    predicted_label: Literal["low_risk", "high_risk"]
    risk_score: float = Field(..., ge=0.0, le=1.0)
    confidence: float = Field(..., ge=0.0, le=1.0)

    # SHAP / feature-level evidence
    # Backward-compatible general ET evidence
    top_eye_tracking_evidence: List[EvidenceItem] = Field(default_factory=list)

    top_fixation_evidence: List[EvidenceItem] = Field(default_factory=list)
    top_saccade_evidence: List[EvidenceItem] = Field(default_factory=list)
    top_metric_evidence: List[EvidenceItem] = Field(default_factory=list)

    top_linguistic_evidence: List[EvidenceItem] = Field(default_factory=list)
    top_interaction_evidence: List[EvidenceItem] = Field(default_factory=list)

    global_reading_patterns: List[str] = Field(default_factory=list)

    # Domain-aware interpretation
    difficulty_pattern: str
    specific_difficulties: List[DifficultyItem] = Field(default_factory=list)

    # Short natural-language specialist explanation
    explanation: str


class BoardReport(BaseModel):
    """
    Output schema for the Assessment Board Agent.

    Board responsibility:
    - integrate all three specialists,
    - decide final risk level,
    - summarize concrete difficulties,
    - generate expert-facing intervention suggestions,
    - communicate uncertainty.

    Board is the only agent that should produce intervention_suggestions.
    """

    final_risk_level: Literal["low_risk", "high_risk"]
    overall_confidence: float = Field(..., ge=0.0, le=1.0)
    agreement_level: Literal["low", "medium", "high"]

    integrated_rationale: str

    # Concise expert-facing summaries
    specific_difficulty_summary: List[str] = Field(default_factory=list)
    intervention_suggestions: List[InterventionSuggestion] = Field(
        default_factory=list
    )

    uncertainty_note: str
    recommendation: str

class CriticIssue(BaseModel):
    issue_type: Literal[
        "calibration",
        "agreement",
        "confidence",
        "evidence_consistency",
        "safety",
        "specificity",
        "conciseness",
        "intervention",
    ]
    severity: Literal["minor", "major", "blocking"]
    message: str
    evidence: str
    required_board_action: str


class CriticReport(BaseModel):
    """
    Critic only reviews the Board draft.
    Critic must NOT produce final risk level, final recommendation, or final intervention suggestions.
    """

    verdict: Literal["pass", "revise"]
    issues: List[CriticIssue] = Field(default_factory=list)
    overall_comment: str

class FinalAssessmentReport(BaseModel):
    subject_id: str

    specialist_reports: List[SpecialistReport]
    board_report: BoardReport
    critic_report: CriticReport

    final_assessment: BoardReport