"""
    state.py: Define shared state for the whole LangGraph workflow.
"""

from typing import Any, Dict, List, TypedDict

class GraphState(TypedDict, total=False):
    case_csv: str
    subject_id: str
    output_dir: str
    mode: str # optional: "demo", "cv", "holdout"

    # ----- Loaded case data -----
    case_row: Dict[str, Any]

    # ----- Specialist agent outputs -----
    syllables_report: Dict[str, Any]
    meaningful_report: Dict[str, Any]
    pseudotext_report: Dict[str, Any]

    # ----- Higher-level agent outputs -----
    board_report: Dict[str, Any]
    board_draft_report: Dict[str, Any]
    board_final_report: Dict[str, Any]
    critic_report: Dict[str, Any]

    # ----- Control flags -----
    need_revision: bool
    errors: List[str]

    # ----- Final result -----
    final_report: Dict[str, Any]

    # ------------------------------------------------------------------
    # Dynamic model paths
    # Used by evaluation folds or final holdout testing
    # If absent, the system can fall back to default paths in config.py
    # ------------------------------------------------------------------
    syllables_model_path: str
    meaningful_model_path: str
    pseudotext_model_path: str

    # Optional explanation profile generated by prepare_features_with_aoi.py
    # Example: data/processed/aoi_profiles.json
    aoi_profile_json: str
